### PR TITLE
chore: update affinity to 2.5.7

### PR DESCRIPTION
**Pull request by 74k1**
Hi there!

Just recently found this repo and wanted to try it out. Unfortunately I already had a newer version of the installation files.
I hope this is correct. I used `nix-hash --type sha256 <file>` for each .exe installer.

### CODE REVIEW

**Comment by mrshmllow** [comment]
beat me to it this morning

**Comment by mrshmllow** [comment]
Unfortunately these hashes look incorrect

**Comment by 74k1** [comment]
Sorry :pensive:, I haven't read the manpage of `nix-hash` before - still pretty new to Nix.
I used `nix-hash --type sha256 --flat --base32 <filename>` now.
Does this work?

**Comment by mrshmllow** [comment]
These look correct. Thank you! I always use `nix-prefetch-url --type sha256 file:///home/....`

**Pull request merged**
